FROM ubuntu:20.04

#install postgres
RUN apt-get update && apt-get install wget ca-certificates gnupg2 vim -y
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
#RUN apt-get update && apt-get install postgresql postgresql-contrib -y

# install Python 3
RUN apt-get update && apt-get install -y python3 python3-pip

#Copy Script into image
COPY create_user.py /
RUN chmod 0755 create_user.py

# install psycopg2 library with PIP
RUN apt-get install -y libpq-dev
RUN pip3 install psycopg2
